### ISSUE TITLE
Glow command is not available

### ISSUE THREAD

**Issue by rluetzner** [ellisonleao/glow.nvim#103]
I'm pretty sure this is an error on my side, but I can't figure out what I'm doing wrong.

I'm using vim-plug as a plugin manager and so far other plugins seem to be working fine. `glow.nvim` is also installed correctly, but the `:Glow` command is simply not available in nvim.

Here's my config:

```bash
call plug#begin('~/.vim/plugged')
  Plug 'tpope/vim-sensible'
  Plug 'tpope/vim-fugitive'
  Plug 'ellisonleao/glow.nvim'
  Plug 'Mofiqul/dracula.nvim'
call plug#end()

colorscheme dracula
au FileType gitcommit setlocal tw=72
filetype plugin indent on
syntax on
```

I'm using `NVIM v0.8.2` and the latest commit for glow.nvim `77b5cb1`.

----

Edit: I forgot to mention that glow itself is of course installed. It's an "unknown" version, because I installed it from source with `go install`, but it's the latest version as of today.

**Comment by rluetzner** [comment]
That is definitely related to the latest commit on [master](https://github.com/ellisonleao/glow.nvim/commit/77b5cb1235c3a7d9be9d8cf6e0454d2528414911).

If I do the following:

```text
Plug 'ellisonleao/glow.nvim', { 'commit': 'c88184a' }
```

The Glow command is there. However, I run into the same issues as reported in #90 .

**Comment by ellisonleao** [comment]
hey @rluetzner sorry, I need to update README, but now you will need to call the glow setup command to create it. Can you put in your config:

```vim
lua << EOF
require("glow").config()
EOF
```

and try again please?

**Comment by rluetzner** [comment]
@ellisonleao , I tried that, but it errors out on me:

```text
Error detected while processing /home/robertl/.config/nvim/init.vim[3]../home/robertl/.vimrc:
line   21:
E5108: Error executing lua [string ":lua"]:1: attempt to call field 'config' (a table value)
stack traceback:
        [string ":lua"]:1: in main chunk
```

**Comment by ellisonleao** [comment]
@rluetzner oops, sorry again. Updated the command in the previous msg

**Comment by rluetzner** [comment]
Thank you. It's working now. Feel free to close this once you've updated the README. 🙂
