### ISSUE TITLE
Update to latest glow version

### ISSUE THREAD

**Issue by ellisonleao** [ellisonleao/glow.nvim#104]

**Comment by pyqlsa** [comment]
When testing the latest version of glow, I found some odd behavior.  I've submitted https://github.com/ellisonleao/glow.nvim/pull/107, as this fix appears to work for me.  Please feel free to let me know what you think!

**Comment by pyqlsa** [comment]
@ellisonleao friendly bump

**Comment by ellisonleao** [comment]
Added in #107
