### ISSUE TITLE
Auto jump to current location in preview window / Show markdown in splits?

### ISSUE THREAD

**Issue by CalebDW** [ellisonleao/glow.nvim#106]
Hello!

I'm editing a large markdown file, and when I preview the markdown it always jump to the top of the file. Would it be possible to auto jump to the current location?

Also, it would be pretty neat to be able to split the screen and see the rendered markdown in the split auto-update as you're editing the markdown file.

**Comment by ellisonleao** [comment]
hey @CalebDW those are great suggestions. We are already discussing them [here](https://github.com/ellisonleao/glow.nvim/discussions/79) and [here](https://github.com/ellisonleao/glow.nvim/discussions/78). Feel free to add your comments there
