### ISSUE TITLE
Glow binary is not installed

### ISSUE THREAD

**Issue by ofsaleem** [ellisonleao/glow.nvim#108]
hi, i've tried the latest version on macos ventura and on debian bullseye. i don't see any error messages during :PlugInstall or :PlugUpdate, but the Glow binary is not put into .local/bin and so the plugin doesn't work. using neovim and vim-plug

**Comment by ofsaleem** [comment]
oh, i do have `require('glow').setup()` in my init.vim as well

**Comment by ellisonleao** [comment]
hey @ofsaleem what does 

```
:lua vim.pretty_print(require('glow').config)
```
shows you?

**Comment by ofsaleem** [comment]
```
  border = "shadow",
  glow_path = "",
  height = 100,
  install_path = "/Users/omar/.local/bin",
  mouse = false,
  pager = false,
  style = "dark",
  width = 100
}
```

it's similar on my linux systems, /home/omar/.local/bin, in all cases that directory exists but doesn't contain the Glow binary

**Comment by mcookly** [comment]
I have this same issue. Nothing is installed to `.local/bin`.

**Comment by ellisonleao** [comment]
@mcookly what is your OS? 

@ofsaleem do you get any errors on running the `:Glow` command?

**Comment by mcookly** [comment]
@ellisonleao I'm running MacOS Ventura 13.1 Intel

**Comment by zanglg** [comment]
I have a similar issue, but I have already install the glow by home-brew.

``` plain
    1 # vm-virtio
    2
    3 The `vm-virtio` workspace provides
    4 [virtio](https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=virtio)
    5 abstractions┌────────────────────────────────────────────────────────────────────────────────────┐
    6 consists of │                                                                                    │
    7             │                                                                                    │
    8 - `virtio-bi│                                                                                    │
    9   kernel API│                                                                                    │
   10 - `virtio-bl│                                                                                    │
   11   the block │                                                                                    │
   12 - `virtio-co│                                                                                    │
   13 - `virtio-de│                                                                                    │
   14   virtio dev│                                                                                    │
   15   transport │                                                                                    │
   16 - `virtio-qu│                                                                                    │
   17             │                                                                                    │
   18 - `virtio-qu│                                                                                    │
   19    deseriali│                                                                                    │
   20 - `virtio-vs│                                                                                    │
   21             │                                                                                    │
   22 ### Note    │                                                                                    │
   23 We offer sup│                                                                                    │
   24 ([the legacy│                                                                                    │.html#x1-60001)
   25 is not suppo│                                                                                    │
   26             │                                                                                    │
   27 The queues a│                                                                                    │
   28 the guest dr│                                                                                    │
   29 block device│                                                                                    │
   30 communicatio│                                                                                    │
   31 transport op│                                                                                    │
   32 In addition └────────────────────────────────────────────────────────────────────────────────────┘
   33 the VMM has to also define the device backend and the event handling mechanism.
   34
   35 ## The `Queue` abstraction
 NORMAL   main  [No Name] [-]                                               utf-8     glowpreview  Top    1:1
```

``` lua
:lua vim.pretty_print(require('glow').config)
{
  border = "single",
  glow_path = "/usr/local/bin/glow",
  height = 100,
  install_path = "/Users/zanglg/.local/bin",
  mouse = false,
  pager = false,
  style = "dark",
  width = 100
}
```

**Comment by ofsaleem** [comment]
> @mcookly what is your OS?
> 
> @ofsaleem do you get any errors on running the `:Glow` command?

this is embarrassing but it works now, and the binary exists into the .local/bin folder. i'm not sure if running `:Glow` or the `lua` line earlier is what did it, but it was one of them!

**Comment by ellisonleao** [comment]
@ofsaleem when you call `:Glow` command without setting glow bin path, the plugin tries to find it automatically if it's in your `$PATH`, then it will try to install it in the background if doesn't

**Comment by ellisonleao** [comment]
@zanglg the issue you are facing is probably related to #107 
Can you check if you have installed the latest version?

**Comment by ofsaleem** [comment]
> @ofsaleem when you call `:Glow` command without setting glow bin path, the plugin tries to find it automatically if it's in your `$PATH`, then it will try to install it in the background if doesn't

I see. I guess I was confused because I thought calling setup would do this. I did not try to use the plugin when I knew the binary wasn't there in the path it was looking for it. Do you think maybe the setup should make that check/installation rather than :Glow?

**Comment by zanglg** [comment]
@ellisonleao YES. It's 1.5.0

**Comment by ellisonleao** [comment]
@zanglg please fallback to 1.4.1 until #107 is done

**Comment by ellisonleao** [comment]
@ofsaleem i don't think it's a good idea to be honest, we had several issues in the past so I am also considering removing the auto installation part because there are just too many edge cases going on, so we would simply try the best effort to download your OS version when you call the Glow command (if its not installed yet)

**Comment by ellisonleao** [comment]
@mcookly unfortunately I don't have an immediate solution for this OS. Can you try installing glow manually via homebrew (*PLEASE* use version 1.4.1 until #107 is done) and try again?

**Comment by zanglg** [comment]
> @zanglg please fallback to 1.4.1 until #107 is done

Ok, thanks. I've tried 1.4.1 and it works.

**Comment by niksingh710** [comment]
`go install github.com/charmbracelet/glow@v1.4.1`
Made it working for now.
waiting for the pr to be merged #107

**Comment by ellisonleao** [comment]
cool, closing this one them

**Comment by edte** [comment]
same issues, i fix it by:


```
go install github.com/charmbracelet/glow@v1.4.1
```

it download at ~/go/bin/glow, i copy it to ~/.local/bin 
```
cp ~/go/bin/glow ~/.local/bin
```

and configure

```
require('glow').setup({
    glow_path = "/Users/edte/.local/bin/glow",
})

```

finally,it works.
