### ISSUE TITLE
Weird Markdown preview

### ISSUE THREAD

**Issue by attilarepka** [ellisonleao/glow.nvim#111]
Hello,
After upgrading to latest version of glow.nvim (no idea from which version I jumped to latest), highlighting is weird **red** on my neovim, see attached screenshot.
![image](https://user-images.githubusercontent.com/39063661/218150563-d543ea7c-f1b1-45a6-8f34-3906f20b2df7.png)

Setup information:
- Neovim v0.8.2
- Ubuntu 22.02
- Terminal emulator `terminator`, but same effect happens in `gnome-terminal`

Further notes:
- Glow does work perfectly when invoked directly via terminal (1.4.1 (4863f57))
- glow.nvim markdown preview panel is working, able to scroll, quit, etc.

My `init.vim` config can be found [here](https://github.com/attilarepka/neovim-config/blob/master/init.vim)

Any suggestions on this one, please?

Kind Regards!

**Comment by attilarepka** [comment]
Turns out it was due to my trailing whitespace highlighting:

`highlight ExtraWhitespace ctermbg=red guibg=red`

But this wasn't causing any issues in the previous versions.

**Comment by attilarepka** [comment]
The workaround for me was simply replacing the trailing whitespace method in my `init.vim` file:
https://github.com/attilarepka/neovim-config/commit/56023dc7775c15914766ce40795c202530d3771c

Maybe a hint for others, if they have similar issues.

**Comment by ellisonleao** [comment]
cool, thanks for sharing
