### ISSUE TITLE
Glow Window Empty

### ISSUE THREAD

**Issue by ananthb** [ellisonleao/glow.nvim#112]
The Glow window that opens up is empty in my terminal and in Neovide.

<img width="1021" alt="Screenshot 2023-02-13 at 17 02 49" src="https://user-images.githubusercontent.com/3133350/218447072-b5780edb-8c25-49f3-8d58-1b05a21f829e.png">

**Comment by ellisonleao** [comment]
@ananthb are you using latest glow version?

**Comment by ananthb** [comment]
Yes I'm using version 1.5.0.

**Comment by ellisonleao** [comment]
Please rollback to 1.4.1 until #104 is done
