### ISSUE TITLE
Syntastic and glow.nvim: Undefined variable: w:syntastic_wid

### ISSUE THREAD

**Issue by heywoodlh** [ellisonleao/glow.nvim#116]
When using Syntastic with glow.nvim I get the following error when I exit the buffer that `:Glow` opens:

```
Undefined variable: w:syntastic_wid
```

Adding the following to my `~/.vimrc` resolved this (it defines the `w:syntastic_wid` variable for buffers opened with `:Glow`):

```
augroup set_syntastic_wid_for_glow
  autocmd!
  autocmd BufEnter glow* let w:syntastic_wid=win_getid()
augroup END
```

It'd be cool to have a fix implemented in glow.nvim, but for now I'm happy to have a workaround.

**Comment by ellisonleao** [comment]
Not sure if this is a glow related issue. Can you maybe try to open an issue in syntactic repo to check if they already had this kind of problem before?

**Comment by heywoodlh** [comment]
I also don't think this is necessarily a glow issue. Was more just posting for visibility for glow.nvim users to have a workaround.

**Comment by ellisonleao** [comment]
Cool, thanks for that @heywoodlh !
