### ISSUE TITLE
Glow shows a blank screen

### ISSUE THREAD

**Issue by dasShounak** [ellisonleao/glow.nvim#117]
Whenever I try to preview any markdown file using `:Glow` command, a blank floating window pops up.
I am using the default configuration.

![image](https://user-images.githubusercontent.com/69243195/226519278-d3037b9b-ac3d-4fe7-8581-fd08adce9a93.png)

**Comment by ellisonleao** [comment]
@dasShounak are you using latest plugin version? What OS and neovim version are using as well? Can you share a minimal config to reproduce it?

**Comment by johnhampton** [comment]
@dasShounak Updating to the latest plugin version fixed the issue for me.

**Comment by dasShounak** [comment]
@johnhampton ahh… I might sound dumb, but how do you update a plugin to the latest version?

**Comment by dasShounak** [comment]
@ellisonleao I just installed the plugin with packer
```sh
use {"ellisonleao/glow.nvim", config = function() require("glow").setup() end}
```
I am using nvim v0.8.3 on fedora

**Comment by ellisonleao** [comment]
Can you call `:PackerSync` just to make sure you are on latest?

**Comment by dasShounak** [comment]
Yeah, I'm on the latest

**Comment by ellisonleao** [comment]
Did you already installed the glow binary (not the plugin) before installing the plugin?

**Comment by dasShounak** [comment]
No I didn't.

**Comment by ellisonleao** [comment]
@dasShounak Can you show the output of 

```
:lua vim.pretty_print(require('glow').config)
```
please?

**Comment by dasShounak** [comment]
Sure. Here's the output:
```
{
  border = "shadow",
  glow_path = "/home/c3rb/.local/bin/glow",
  height = 100,
  install_path = "/home/c3rb/.local/bin",
  mouse = false,
  pager = false,
  style = "dark",
  width = 100
}
```

**Comment by ellisonleao** [comment]
Seems okay. unfortunately, i can't reproduce your issue on my side using a fresh install. Can you try:

1. remove the glow installation from `/home/c3b/.local/bin/glow`
2.  call `:PackerSync` again
3.  call `:Glow` for an unmodified md file 
4. call `:Glow <file>` for an unomodifield md file in another path then pwd
5. call `:Glow` in a modified md file (open some md file, make some modifications, do not save, call :Glow)

**Comment by dasShounak** [comment]
It worked! Thanks a lot.
