### ISSUE TITLE
[glow] could not execute glow binary in path= .   in Windows 10

### ISSUE THREAD

**Issue by chenchongpal** [ellisonleao/glow.nvim#122]
![error_neovim](https://user-images.githubusercontent.com/49556943/232679639-01a12002-b7e4-4daf-ae64-8795195fcdc6.png)
![error_terminal](https://user-images.githubusercontent.com/49556943/232679648-6ad68bc6-0f12-45e5-a1d3-499da898b6c6.png)
**Describe the bug**
- Neovim [0.9.0]
- glow.nvim [0.2.0-1]
- glow [1.5.0]
- Windows 10

**To Reproduce**
1. I have installed glow and neovim using scoop, and cloned the LazyVim
2. I have tried:
install_path = "D:\scoop\apps\glow\current",
install_path = "D:\\scoop\\apps\\glow\\current",
install_path = "D:/scoop/apps/glow/current",
install_path = "D:\scoop\apps",
install_path = "D:\\scoop\\apps",
install_path = "D:/scoop/apps",
install_path = "../../glow",
in ~/AppData/Local/nvim/config/plugins/glow.lua

3. Error: [glow] could not execute glow binary in path= . make sure you have the right config

**Expected behavior**
Dose glow.nvim support Windows operation system?

**Screenshots**
![图片](https://user-images.githubusercontent.com/49556943/232676868-aaa07308-bbba-4211-9a39-dfbedc69442a.png)
![图片](https://user-images.githubusercontent.com/49556943/232677892-33d159a1-3071-48f8-8f7e-0f639aa14089.png)

**Comment by ramfattah** [comment]
Hi @chenchongpal, 

I'm getting the same error. I'm new to neovim; Could you please clarify what do you mean by `set event = "VimEnter"`? 

I'm using astronvim distro.
![image](https://github.com/ellisonleao/glow.nvim/assets/38049078/78025f3b-143d-4949-9782-1e32600b3366)

My "plugins/glow.lua" file:
```lua
return { "ellisonleao/glow.nvim", config = true, cmd = "Glow" }
```

**Comment by chenchongpal** [comment]
您的邮件已收到，谢谢。

**Comment by ramfattah** [comment]
It's solved now, not sure how i did it. Sharing the steps i took:
1. Install `Glow` using Homebrew.
2. Restarted the terminal.
