### ISSUE TITLE
Run Glow with Lua command

### ISSUE THREAD

**Issue by kevintraver** [ellisonleao/glow.nvim#132]
What are the arguments for running with the **_lua_** command?

I tried this but it does not seem to work:

 `require("glow").execute()`

`require("glow").execute('%')`

**Comment by mattbun** [comment]
Hey I've been trying to do the same thing! It's looking for an array called `fargs` containing the path to the file. You can call it like this:

```lua
require("glow").execute({
  fargs = {
    vim.fn.expand("%"),
  },
})
```

**Comment by kevintraver** [comment]
That works! Thanks!
