### ISSUE TITLE
Glow Preview completely blank in Powershell

### ISSUE THREAD

**Issue by kvietcong** [ellisonleao/glow.nvim#18]
**Describe the bug**
I try running `:Glow` on Windows with Powershell 7.1.3 but the popup window is completely blank.

If I go into insert mode in the floating window and press enter I get the message `An unknown element "" was received. This can happen if the remote process closed or ended abnormally`

Weirdly enough, it works perfectly well with the original cmd shell.

While this plugin probably doesn't have Windows too high on its compatibility list, I would appreciate any help.

**To Reproduce**
Set the shell to `pwsh` or `powershell`
Run `:Glow`

**Expected behavior**
There will be a markdown preview in the pop up window

**Additional context**
Neovim Version: NVIM v0.5.0-dev+1233
OS: Windows 10
Terminal: Windows Terminal 1.8.14444.0

**Comment by ellisonleao** [comment]
So you are saying that the `glow` command works outside neovim but not inside? can you share some screenshots please? Unfortunately I don't have a way to test on Windows machines now.

**Comment by kvietcong** [comment]
## PowerShell in regular terminal:
![image](https://user-images.githubusercontent.com/32186663/120092520-4e06e900-c0c8-11eb-91b5-35d8143a5de7.png)

## CMD in regular terminal:
![image](https://user-images.githubusercontent.com/32186663/120092529-6840c700-c0c8-11eb-8607-ea7308e9a28e.png)

## Neovim with CMD shell:
![image](https://user-images.githubusercontent.com/32186663/120092533-81497800-c0c8-11eb-81f3-8b72652cdf00.png)

## Neovim with Powershell shell:

### Initial:
![image](https://user-images.githubusercontent.com/32186663/120092556-ab029f00-c0c8-11eb-941f-a584a4530a09.png)

### After going into insert mode and pressing enter 2 times:
![image](https://user-images.githubusercontent.com/32186663/120092563-b229ad00-c0c8-11eb-9af3-7f2c77eee33f.png)

**Comment by shift-d** [comment]
Can reproduce this issue...

**Comment by kvietcong** [comment]
Yeah, it was reproducible with the old init.vim I had. However, I did find a fix. I forgot about this issue b/c I stopped using glow after a while, so sorry about that. You just need to put this in your init.vim to fix many Powershell issues.

```
if has("win32") || has("win64")
    " Make Powershell work :)
    let &shell = "pwsh"
    let &shellcmdflag = '-NoLogo -NoProfile -ExecutionPolicy RemoteSigned -Command [Console]::InputEncoding=[Console]::OutputEncoding=[System.Text.Encoding]::UTF8;'
    let &shellredir = '2>&1 | Out-File -Encoding UTF8 %s; exit $LastExitCode'
    let &shellpipe = '2>&1 | Out-File -Encoding UTF8 %s; exit $LastExitCode'
    set shellquote= shellxquote=
endif
```
