### ISSUE TITLE
Error occurred during installation on Windows

### ISSUE THREAD

**Issue by pluma9** [ellisonleao/glow.nvim#19]
## Description

When running `:PlugInstall` to install the plugin, I encountered this error:
`E5108: Error executing lua Vim:E903: Process failed to start: no such file or directory: "/bin/bash"`

## Environment
OS: Windows 10
Nvim: v0.5.0-828-g0a95549d6

**Comment by ellisonleao** [comment]
Yeah the script installation does not support windows for now. Can you try installing manually and having `glow` command available in your %PATH until I have a solution?
