### ISSUE TITLE
Suggested mapping in README

### ISSUE THREAD

**Issue by mnacamura** [ellisonleao/glow.nvim#21]
Hi. Thanks a lot for creating this nice plugin.

In README, the following mapping is suggested.
```vim
nmap <leader>p :Glow<CR>
```
Since this plugin is specific to markdown files, I tried buffer-specific mapping:
```vim
augroup glow
autocmd!
autocmd FileType markdown nnoremap <buffer> <silent> <Space> <Cmd>Glow<CR>
augroup END
```
Unfortunately with this mapping, I cannot toggle the glow preview window by hitting `<Space>` because the mapping is not enabled in the preview buffer.
So my thought about mapping is that it could be better to enable users to customize mapping to toggle (or close) preview window in the preview buffer. What do you think about it?

**Comment by ellisonleao** [comment]
>  I cannot toggle the glow preview window by hitting <Space> because the mapping is not enabled in the preview buffer.

So are you suggesting to have the same mapping added to call the window and to close it? like a toggling feature? The current `:Glow` command already works as a toggle, so if you call the original mapping it will already close the window

**Comment by mnacamura** [comment]
I want to map some key (in the above example, `<Space>`) to `:Glow<CR>` only when file type is markdown, not global. The problem for doing this is that the mapping is not available in the preview buffer. So I proposed enabling to customize mapping to toggle preview window in the preview buffer.

**Comment by ellisonleao** [comment]
This is what i am not  understanding. Do you want a custom mapping to trigger the window AND another one for closing it?

**Comment by mnacamura** [comment]
> Do you want a custom mapping to trigger the window AND another one for closing it?

Yes. More precisely, I need
```vim
augroup glow
autocmd!
autocmd FileType markdown nnoremap <buffer> <silent> <Space> <Cmd>Glow<CR>
augroup END
```
to open a preview window by typing `<Space>` only in markdown file type, AND
```lua
-- In lua/glow.lua around lines 115-118
api.nvim_buf_set_keymap(buf, "n", "<Space>", ":lua require('glow').close_window()<cr>",
                                            {noremap = true, silent = true})
```
to close the preview window, because the above `autocmd` does not work in the preview window.
