### ISSUE TITLE
paq-nvim installation fails

### ISSUE THREAD

**Issue by henriquehbr** [ellisonleao/glow.nvim#30]
Whenever i try to install `glow.nvim` with [`paq-nvim`](https://github.com/savq/paq-nvim), it simply doesn't works, there's no error output, i'm unable to run both `:GlowInstall` and `:Glow`, they give no output at all, my `plugins.lua` file is like this at the moment:

```lua
require 'paq' {
    {'npxbr/glow.nvim', opt = true, run = vim.cmd('GlowInstall')};
}
```

Does glow supports `paq-nvim` or only [`packer`](https://github.com/wbthomason/packer.nvim)?

**Comment by ellisonleao** [comment]
That is so weird. Honestly i am not sure about the paq internals, does that `opt=true` adds the plugin as optional until you call `GlowInstall` manually?

**Comment by henriquehbr** [comment]
Yep, just checked again and the plugin is properly installed on `$XDG_DATA_HOME/nvim/site/pack/paqs/opt/glow.nvim`

Whenever i try to `packadd glow.nvim` then `GlowInstall`, the command isn't recognized

**Comment by ellisonleao** [comment]
are you trying in a markdown file? Sorry, that install command also only works in markdown files for now

**Comment by henriquehbr** [comment]
Removed the `opt` option and tried again on a markdown file and now i can run `GlowInstall`, but... i get the following error during the installation:

![image](https://user-images.githubusercontent.com/31735860/128584831-a8eb9b13-71cd-48b6-a4ca-bea336d96e22.png)

> PS: I was looking around the closed issues, searching for something that might be related to my problem, and the most similar that i could find was #17, but after taking a closer look, i'm not entirely sure if both are related to the same thing

**Comment by ellisonleao** [comment]
hm, is your `/tmp` folder with another permission maybe? the download basically puts the tar file over there, untar it, and moves the binary to $GOPATH/bin.

**Comment by henriquehbr** [comment]
Sorry, but what exactly you mean by another permission?

I have proper permissions to access the `/tmp` directory, another thing that i also noticed is that after trying to install glow through `GlowInstall` and exiting from neovim, it leaves a `glow.tar`gz` on the directory where neovim was started, is it a intended behavior?

**Comment by ellisonleao** [comment]
Can you give me some specs on what is your OS and version please?

**Comment by henriquehbr** [comment]
**os:** Arch Linux x86_64
**kernel:** 5.13.8
**glow:** latest (HEAD -> 3688c38)
**nvim:** 0.5.0

**Comment by michzappa** [comment]
I have the same error and misplace glow.tar.gz as @henriquehbr on a Debian 9 server.

**Comment by H4nYolo** [comment]
@henriquehbr 

fixed it by installing glow manually: https://github.com/charmbracelet/glow

**Comment by ellisonleao** [comment]
Guys i've fixed the GlowInstall command creation now and we had an update also in the install script. Can you guys pull latest and try again please?

**Comment by henriquehbr** [comment]
@H4nYolo many thanks for the suggestion, it worked for me as well!

@ellisonleao tried again with the latest version and got the same problem from the previous screenshot, looks like i can't install glow through `:GlowInstall`, but whenever i try to run `:Glow` with a pre-installed binary, it works fine, probably the problem might be on the way `:GlowInstall` handles the installation process

**Comment by ellisonleao** [comment]
guys, new bugfix attempt was pushed. can you try again please?

**Comment by henriquehbr** [comment]
I got the following error message when running `:GlowInstall`:

```
installing glow..
OS not supported/recognized!
```

**Comment by ellisonleao** [comment]
@henriquehbr can you give the output for:

`uname`, `uname -a` and `uname -p` please?

**Comment by henriquehbr** [comment]
#### `uname`

```
Linux
```

#### `uname -a`

```
Linux bonfire 5.13.13-arch1-1 #1 SMP PREEMPT Thu, 26 Aug 2021 19:14:36 +0000 x86_64 GNU/Linux
```

#### `uname -p`

```
unknown
```

**Comment by ellisonleao** [comment]
The GlowInstall command was just removed and a new installation process is in place. Can you pull latest and check if it's working now?
