### ISSUE TITLE
[Feature] Is there an full screen options?

### ISSUE THREAD

**Issue by qvieth** [ellisonleao/glow.nvim#31]
Full screen or change window size feature would be really helpful, but it seems like there isn't one, btw thank you for making this plugin!!

**Comment by ellisonleao** [comment]
no, but we can have configs for window size, let me think about it

**Comment by qvieth** [comment]
@ellisonleao, I almost forgot there's a native solution for this:
- `Ctrl-w + |`  set window's width max
- `Ctrl-w + _` set window's height max
- `:h window-resize` for more `information.`

Map <C-w>z for window's size zoom :
- `vim.api.nvim_set_keymap("n", "<C-w>z", "<C-w>|<C-w>_", { noremap = true, silent = true})`

This works perfectly for my use case, you can close this `issue` if wanted. (I suggest put this information on README so that other users can have a better experience)

**Comment by ellisonleao** [comment]
cool, i will be thinking more on this later, but good suggestion!

**Comment by ramfattah** [comment]
> @ellisonleao, I almost forgot there's a native solution for this:
> 
> * `Ctrl-w + |`  set window's width max
> * `Ctrl-w + _` set window's height max
> * `:h window-resize` for more `information.`
> 
> Map z for window's size zoom :
> 
> * `vim.api.nvim_set_keymap("n", "<C-w>z", "<C-w>|<C-w>_", { noremap = true, silent = true})`
> 
> This works perfectly for my use case, you can close this issue if wanted. (I suggest putting this information on README so that other users can have a better experience - I have opened a pull request for this)

Thanks @qvieth, this worked, except on mac the "w" must be capital `W`.
