### ISSUE TITLE
[feature request] create a preview vertically splitted to left or right.

### ISSUE THREAD

**Issue by alexzanderr** [ellisonleao/glow.nvim#38]
would be very nice to have it right in the right/left side.
would very nice a fresh new reload after buffer save.

**Comment by ellisonleao** [comment]
> would be very nice to have it right in the right/left side.
i actually thought about that when I first started this project, but I find the floating window a little bit better for this specific feature

> would very nice a fresh new reload after buffer save.

not sure if I understand the concept. in the current implementation, since you are moved to the floating window you are not able to make any changes to the markdown file, so I don't think we will have this kinda of feature as well.

**Comment by alexzanderr** [comment]
> i actually thought about that when I first started this project, but I find the floating window a little bit better for this specific feature

you find the floating window `a little better for yourself`.

> not sure if I understand the concept. in the current implementation, since you are moved to the floating window you are not able to make any changes to the markdown file, so I don't think we will have this kinda of feature as well.

im very sure you understand this concept of live update while writing.

thats the idea, the floating window is bad. we want a split to `left or right` to be very easily visible in real time while writing to the markdown file, all of these inside the neovim editor.

thats it. if you are in, then very good. we will appreciate your efforts.

**Comment by ellisonleao** [comment]
> we want a split to left or right to be very easily visible in real time while writing to the markdown file

unfortunately this is not so straightforward. I am sure this is really cool feature, I just don't have the time to work in this right now. Feel free to open a PR and I will gladly review it for sure

**Comment by alexzanderr** [comment]
okey then.
