### ISSUE TITLE
Install Glow binary at $HOME/.local/bin as per Freedesktop.org XDG standards

### ISSUE THREAD

**Issue by mystilleef** [ellisonleao/glow.nvim#39]
I believe the major desktop environments on Linux follow the `XDG` standards. The recommended location to install binaries is in `$HOME/.local/bin`. On most Linux and Linux-like distributions, this location is already in `$PATH`.

Can this be the default location for `Glow`, at least on Linux? It save users from configuring paths, creating new folders, and what not.

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by ellisonleao** [comment]
I've been honestly struggling with this issue for quite some time. Unfortunately, I don't see a clear consensus on what should be the de facto path for local binary folders. I see:
- [`/usr/local/bin`](https://www.pathname.com/fhs/pub/fhs-2.3.html#USRLOCALLOCALHIERARCHY) as one of the most used (but this requires root access)
- [`$HOME/.local/bin`] for modern distros (Debian based mostly) which you provided the XDG page
- [`$HOME/bin`](https://unix.stackexchange.com/a/36874) - I just choose this one for now but I am always open for ideas. Let's wait for other opinions here and maybe check which folder people are really using right now

**Comment by mystilleef** [comment]
> I've been honestly struggling with this issue for quite some time. Unfortunately, I don't see a clear consensus on what should be the de facto path for local binary folders. I see:
> 
> * [`/usr/local/bin`](https://www.pathname.com/fhs/pub/fhs-2.3.html#USRLOCALLOCALHIERARCHY) as one of the most used (but this requires root access)
> * [`$HOME/.local/bin`] for modern distros (Debian based mostly) which you provided the XDG page
> * [`$HOME/bin`](https://unix.stackexchange.com/a/36874) - I just choose this one for now but I am always open for ideas. Let's wait for other opinions here and maybe check which folder people are really using right now

I don't know any major Linux distro that uses anything other than $HOME/.local/bin, or $HOME/.local/usr/bin, for local installation without admin privileges. All major distros follow the XDG spec which is backed by GNOME, KDE, RedHat, OpenSuse, and Debian based distros.

**Comment by academo** [comment]
`$HOME/.local/usr/bin` is standard and mentioned in the XDG specification https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

Beyond that, you can also allow this to come in a configurable way:

* allow to configure the existing glow binary path
* allow to configure the path to use to download the glow binary if not existing
* allow to configure to simply try to use `glow` from the existing $PATH (do not attempt to install)

**Comment by ellisonleao** [comment]
yeah, i am leaning towards having a default path (probably ~/.local/usr/bin or ~/.local/bin) and make that path configurable. Thanks for the feedback guys

**Comment by ellisonleao** [comment]
we now have `g:glow_binary_path` which can be used as the binary destination. It defaults to `$HOME/.local/bin`.  `:GlowInstall` will use it to download and extract over there. If everything goes ok on your side can we close this one?

**Comment by mystilleef** [comment]
> we now have `g:glow_binary_path` which can be used as the binary destination. It defaults to `$HOME/.local/bin`. `:GlowInstall` will use it to download and extract over there. If everything goes ok on your side can we close this one?

It's fixed. I'll close. Great job!
