### ISSUE TITLE
.markdown files not supported

### ISSUE THREAD

**Issue by treeman** [ellisonleao/glow.nvim#40]
I'm getting a "glow only support markdown files" when I try to open a `.markdown` file, even though the filetype is `markdown`. Opening `.md` works well.

**Comment by ellisonleao** [comment]
is .mardown an extension for mardown as well? I am not sure if vim's filetype will work for it

**Comment by treeman** [comment]
I don't think there's a single standard extension for markdown ([see this answer](https://superuser.com/questions/249436/file-extension-for-markdown-files)). I don't know how standard vim does it, but either way I've seen `.markdown` used in different places and I currently use the vimwiki for `.markdown` files well enough.

Maybe "force open the current file" would be an option in case of someone using these weird extensions/filetypes mentioned in the question above?

**Comment by ellisonleao** [comment]
yeah, i am saying this because the `Glow` command is only working for markdown files that vim can understand. I will make some experiments here and let you know how we can handle this. Thanks for the feedback!

**Comment by treeman** [comment]
Awesome, and thank you!

**Comment by ellisonleao** [comment]
@treeman .markdown files are now supported! Please update the latest code and check it out

**Comment by treeman** [comment]
Works great, thanks!
