### ISSUE TITLE
Could not install plugin with Plug

### ISSUE THREAD

**Issue by davidCarlos** [ellisonleao/glow.nvim#41]
Following the readme, i put the following line in my plug.vim

`Plug 'ellisonleao/glow.nvim', {'do': ':GlowInstall', 'branch': 'main'}`

After running `PlugInstall`, I got the following error:
![image](https://user-images.githubusercontent.com/2847027/132096543-3355d0ff-851a-4d40-adf6-a8cf87dbeedc.png)

nvim version: 0.5.0 stable
OS: fedora 40
plugin commit: 794649fa93a49f39e16364da5421508fe0223e4f

**Comment by ellisonleao** [comment]
I've removed that suggestion. You will need to run that command after the plugin is installed now
