### ISSUE TITLE
Glow window colors are messed, depending on user colorscheme 

### ISSUE THREAD

**Issue by davidCarlos** [ellisonleao/glow.nvim#42]
Preview window with onehalfdark colorscheme
![image](https://user-images.githubusercontent.com/2847027/132096999-72d9d42e-e2ce-4eca-a841-2b63170ea722.png)

Preview window with badwolf colorscheme
![image](https://user-images.githubusercontent.com/2847027/132097232-0b8baa91-4fd4-4977-85f8-245f8c915f8c.png)

nvim version: 0.5.0 stable
OS: fedora 40
plugin commit: 794649f

**Comment by ellisonleao** [comment]
hey, @davidCarlos thanks for the report.  Will need to investigate this one because I am not sure if this is related to this plugin. Are you using another plugin that uses floating windows as well? If so, can you verify if they are also having the same issues?

**Comment by davidCarlos** [comment]
1. I made a clean .vim config file, loading only Glow and colorschemes

```
"-------------- general configurations --------------"
syntax on
filetype plugin indent on
"-------------- general configurations --------------"

call plug#begin('~/.config/nvim/plugins')
   Plug 'ellisonleao/glow.nvim', {'do': ':GlowInstall', 'branch': 'main'}
   Plug 'sonph/onehalf', { 'rtp': 'vim' }
   Plug 'sjl/badwolf'
call plug#end()

set termguicolors
colorscheme onehalfdark
```
2. Starting nvim using this config `nvim -u clean.vim`
3. The colors keep messed

I tested this minimal config on kitty and gnome terminal

**Comment by ellisonleao** [comment]
> It's possible that is a bug with onhalf colorscheme specifically, and not on Glow plugin.

yeah, I would say so. Have you tried with another colorscheme just to check?

**Comment by davidCarlos** [comment]
Yes. With badwolf works as expected.

![image](https://user-images.githubusercontent.com/2847027/135911122-d0a1fa53-b0a0-43ee-98a2-f0a37c451e5f.png)

**Comment by ellisonleao** [comment]
Cool, i will close this then since it seems that is not related to this plugin

**Comment by bryceyang** [comment]
> My terminal is in light solarized, my nvim is configured with light solarized as well `background=light`. If I run glow in my terminal, it correctly detects the light background and run in light style. If I run it in neovim, it will run in dark mode which has no contrast on the light background. For reference: https://github.com/charmbracelet/glow#styles

![image](https://user-images.githubusercontent.com/9302617/140299017-429ceb66-37b0-413e-8f8b-15e0a44b31e2.png)

@tissieres  this does the trick. glow itself can set color style. when we use a light theme, we have to set `glow -s` to light.

Is there a way  to pass args to glow through glow.nvim? @ellisonleao

**Comment by tissieres** [comment]
Yes, I did the same.

**Comment by ellisonleao** [comment]
@bryceyang not yet, i am working in a `setup()` function where we will have several configs. I hope to get it done soon

**Comment by onionka** [comment]
Hi @ellisonleao, I know this ticket is closed, but have just one question regarding fixing this issue (workaround).
How could I override color scheme of Glow?
I mean, you wrote to README that we can set up glow json, but where it is please?
