### ISSUE TITLE
Live editing

### ISSUE THREAD

**Issue by sethidden** [ellisonleao/glow.nvim#43]
Is glow.nvim's main intention to be a .md reader - eg. "there's this .md file in my project's documentation. I'm reading it in neovim. It's a bit painful to read raw markdown so I'll use glow.nvim"?

Would something like having two splits side by side:
*  one with the .md file (regular editable nvim buffer)
*  one with the glow preview (that updates live whenever you write something in the .md file, and is also scroll-locked to the .md pane) on the right be outisde of the scope of this project?

Live editing is already possible in https://github.com/iamcco/markdown-preview.nvim but it requires opening a separate browser window. glow.nvim is entierly vim based

**Comment by ellisonleao** [comment]
Live editing is not part of the plans for this plugin, but it could be a very nice feature indeed. The main idea is to edit first and toggle the preview after, so I think I will keep it this way for now.
