### ISSUE TITLE
Feature: Open new split window to preview side-by-side

### ISSUE THREAD

**Issue by DrJackilD** [ellisonleao/glow.nvim#59]
It will be great to have an option when we could open MD file in the new split (or just a new buffer) and observe live changes (not sure if it's doable with Glow tho)

**Comment by danielyrovas** [comment]
Perhaps refresh glow on write? It would be good if #26 was implemented so it wasn't jumping around on each refresh. Opening in a split is definitely attractive to me.

**Comment by ellisonleao** [comment]
Moving this to a new discussion topic here https://github.com/ellisonleao/glow.nvim/discussions/78
