### ISSUE TITLE
Glow.nvim with math expression(LaTex)

### ISSUE THREAD

**Issue by YuCao16** [ellisonleao/glow.nvim#62]
Sorry I have not found document related to using Glow.nvim with markdown file that include LaTeX formulas. And so far it seems that if markdown files include LaTex formula such as `$$x^2$$`, Glow.nvim will skip this line (the whole line). At the same time, I'm using vim.markdown and it could display correctly. 
Did I do something wrong or miss any documents?

**Comment by ellisonleao** [comment]
this is probably an issue for the main glow project, which seems [out of scope](https://github.com/charmbracelet/glow/issues/312).

> At the same time, I'm using vim.markdown and it could display correctly.

can you elaborate on that ? are you using concealing

**Comment by YuCao16** [comment]
> 

I did use concealing, but I don't know exactly how vim.markdown did that, and here below is what it looks like:(I only set `let g:vim_markdown_math = 1` in my init.vim file.)
<img width="98" alt="image" src="https://user-images.githubusercontent.com/62466929/149190136-6339b711-8158-4770-bc66-9b460b1803d6.png">

I mean if It can't display the math expression, it's fine, I can still see them in other ways. However, if it make the whole line disappear, that would be an issue. so is it possible you gonna fix it?

Thanks for your work anyway, I love glow.nvim, it's an amazing tools.

**Comment by YuCao16** [comment]
Sorry my bad, if I save the file it will display correctly, so I have to save my file before call `:Glow` ?

**Comment by ellisonleao** [comment]
@YuCao16 unfortunately for now, yes. We can work on getting this better later, but for now, you will still have to save it first

**Comment by YuCao16** [comment]
Got it, thanks
