### ISSUE TITLE
[vim-plug] Not an editor command: GlowInstall

### ISSUE THREAD

**Issue by grun00** [ellisonleao/glow.nvim#68]
Hey, so I tried installing this with vim-plug and I'm getting a `E492` when trying to run GlowInstall

My nvim is v0.6.0

**Comment by ellisonleao** [comment]
hey @grun00 how are you installing it? are you using latest version?

**Comment by grun00** [comment]
I'm using the latest version of vim-plug, with version 0.6.0 from nvim. I just run :PlugInstall with the relevant line on my `init.vim` (Plug 'ellisonleao/glow.nvim'). When I check the plugin folder, it seems like it's all there:

```
~ ❯ cd /home/grun/.local/share/nvim/plugged/glow.nvim/                                                                                                                                              took  1m 7s
~/.local/share/nvim/plugged/glow.nvim on   main ❯ ls
LICENSE  lua  Makefile  plugin  README.md  tests  vendor
~/.local/share/nvim/plugged/glow.nvim on   main ❯ git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
~/.local/share/nvim/plugged/glow.nvim on   main ❯ git log
commit 64052ad16286281861de9281dc0695c80cc9ccc4 (grafted, HEAD -> main, origin/main, origin/HEAD)
Author: Ellison Leão <ellisonleao@gmail.com>
Date:   Thu Mar 10 16:52:42 2022 -0300

    new project structure
~/.local/share/nvim/plugged/glow.nvim on   main ❯
```

Hope that info is relevant. Do you have any idea of what might be the problem?

**Comment by ellisonleao** [comment]
Closing this issue since the new code has remove this function and now the installation process is handled inside the plugin
