### ISSUE TITLE
"OS not supported/recognized" on M1 Macbook

### ISSUE THREAD

**Issue by covercash2** [ellisonleao/glow.nvim#69]
I'm not sure what the effort is to support the M1. I just got this new laptop and was looking to migrate away from emacs for my notes (it doesn't work great on M1 either). I haven't looked much into the code for why this isn't working. let me know if there's any more info I can provide

**Comment by ellisonleao** [comment]
hey @covercash2 thanks for the reporting this. I am working on getting the Windows and M1 support a little bit better, but in the meantime, can you try to install the [latest glow binary ](https://github.com/charmbracelet/glow/releases/tag/v1.4.1)and see if its works in your terminal ?

**Comment by covercash2** [comment]
glow works for sure 👍

**Comment by ellisonleao** [comment]
New config system and installation process is now in the main branch. Can you guys check if everything is working, please?
