### ISSUE TITLE
Magenta background

### ISSUE THREAD

**Issue by mickepojken** [ellisonleao/glow.nvim#71]
Hey! Trying out glow, but for some reason the background is magenta. It's persisent across both the built in light and dark theme and other colour schemes for my terminal. Any ideas why? Here's a screenshot. Using neovim on arch. Terminal is alacritty.
![2022-04-14-14-41-12_](https://user-images.githubusercontent.com/97978235/163392682-291cddc2-0c07-43ed-a23c-422a8f11d01b.png)

**Comment by ellisonleao** [comment]
do you have the same output using it directly in the terminal?

**Comment by mickepojken** [comment]
No, there it's fine.

**Comment by marco7m** [comment]
I had the same issue here. One thing I noticed is that the same background color is on the menu that appears when I type " : " (bottom-left of the printscreen) (I also want to change that but don't know how)

![image](https://user-images.githubusercontent.com/11334546/175437368-4c29de75-fbd4-4f5a-9cd3-f5e1273a9b2b.png)

**Comment by ellisonleao** [comment]
hey guys, can you share some configs please? i am wondering if this is a missing `termguicolors` option issue

**Comment by ellisonleao** [comment]
We were closing this since we still got no response so far. If the issue still persists, please open a new one
