### ISSUE TITLE
OS not supported

### ISSUE THREAD

**Issue by mengano-net** [ellisonleao/glow.nvim#82]
Hi:

Great plugin by the way, thanks for your efforts.

I upgraded nvim at some point in the recent past, now :Glow won't run, I'm not sure what changed, here is my config:

- nvim version
```
❯ nvim --version
NVIM v0.8.0-dev+555-gd07a39c54
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/runner/work/neovim/neovim/build/cmake.config -I/Users/runner/work/neovim/neovim/src -I/Users/runner/work/neovim/neovim/.deps/usr/include -I/Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/include -I/Library/Frameworks/Mono.framework/Headers -I/Users/runner/work/neovim/neovim/build/src/nvim/auto -I/Users/runner/work/neovim/neovim/build/include
Compiled by runner@Mac-1656995109108.local

Features: +acl +iconv +tui
See ":help feature-compile"
```
- macOS Monterry 12.5
- `:lua print(vim.loop.os_uname().sysname)` = "Darwin"
- I use `wbthomason/packer.nvim` to manage my plugins, this is my :Glow snippet:
```
  use({
    "ellisonleao/glow.nvim",
    branch = "main",
    config = {
      function()
        require("glow").setup({
          border = "rounded",
          width = 100,
        })
      end,
    },
  })
```

**Comment by mengano-net** [comment]
More details that will hopefully aid troubleshooting

```
❯ .local/bin/glow --version
glow version 1.4.1 (4863f57)
❯ .local/bin/glow test.md

  This is a test

  test

  italics

  This is a test that I'm writing to see if this dam thing gets wrapped automatically, in fact I'm checking several
  things here.

  This is yet another paragraph that I'm writing to check this thing or this other thing and figure out wrapping

   Header

  ## HEADER 2

    testing

  This is another test that I'm writing in order to test this  GoYo plugin . To be honest, I'm not sure about it

  Does this mean that a new line starts after having a single space left? Nah, that can't be


~
❯```

**Comment by Ghasak** [comment]
Hi @mengano-net 
I have added a pull request 
[HotFix](https://github.com/ellisonleao/glow.nvim/pull/83/commits/447c02bcc0c28ba71c2a4eb242ef9f83f72d202fl)
I have used the as you suggested `vim.loop.os_uname().sysname` 
instead `jit.os`
You can achieve temporarily until get approved the same at 
`~/.local/share/nvim/site/pack/packer/start/glow.nvim/lua/glow`
Simply by changing the line 
local raw_os = jit.os
to 
local raw_os = vim.loop.os_uname().sysname
I hope this is useful

**Comment by ellisonleao** [comment]
@Ghasak and @mengano-net can you guys show the output for:

```
:lua vim.pretty_print(jit.os)
```

not sure why that env is not working for your OS/arch

**Comment by mengano-net** [comment]
> @Ghasak and @mengano-net can you guys show the output for:
> 
> ```
> :lua vim.pretty_print(jit.os)
> ```
> 
> not sure why that env is not working for your OS/arch

`"OSX"`

**Comment by mengano-net** [comment]
Confirmed fix worked, thanks all.

**Comment by Ghasak** [comment]
Hi @ellisonleao and @mengano-net 
Yes, same for me, 
the output is of jit.os is **OSX** not **Darwin**
