### ISSUE TITLE
Glow in my neovim look weird

### ISSUE THREAD

**Issue by cckcoder** [ellisonleao/glow.nvim#86]
Hi, First of all thx a lot to make great thing, I'd like you help me about weird stuff

![image](https://user-images.githubusercontent.com/25289970/186410732-6f8e48ee-9e0d-4082-ba83-7d79e9209313.png)

as you see in the picture it have | | |

I'm use `Ubuntu 22.04.1 LTS`
and neovim version `NVIM v0.8.0-dev+237-g6e414b698`

**Comment by ellisonleao** [comment]
hey @cckcoder can you show your config please?

**Comment by ellisonleao** [comment]
Closing due to no response. Feel free to reopen
