### ISSUE TITLE
Supporting preview location

### ISSUE THREAD

**Issue by michaeldelgado1** [ellisonleao/glow.nvim#87]
This project is really exciting.  I'm wondering if there are any plans to support changing the location of where the preview window opens. I'm quite comfortable with having my preview to the side of my markdown document. 

Side note:
It could cause confusion as I don't think the preview will update in real time, but maybe a recipe could be made to set up an auto command that re-executes the glow command on save if the window is open.

**Comment by ellisonleao** [comment]
hey @michaeldelgado1 , yes we have plans for that in https://github.com/ellisonleao/glow.nvim/discussions/78. Please make sure to follow the discussion
