### ISSUE TITLE
Glow not rendering markdown---blank window

### ISSUE THREAD

**Issue by CalebDW** [ellisonleao/glow.nvim#90]
Hello,

I updated my glow config to use the new `setup()` function (see below) but now the glow window is empty when trying to preview my file:
```lua
require('glow').setup({
    border = 'rounded',
    pager = false,
    width = 120,
})
```

![image](https://user-images.githubusercontent.com/4176520/189660131-1b156899-3a17-494f-be2e-bb81d5b22606.png)

If I update `pager` to  `true` (not really sure what this option is for...perhaps you could explain in docs?) then I can see the rendered markdown---but only after a keypress and there's some weird behaviour:

<details>

Initial Window:
![image](https://user-images.githubusercontent.com/4176520/189660943-ffef88ed-fc98-4e32-9e4d-18b9714f77a9.png)

After pressing any key:
![image](https://user-images.githubusercontent.com/4176520/189661001-7ed904c7-181a-4fb3-9b2c-d37f21f856e8.png)

After hitting `q` to close preview:
![image](https://user-images.githubusercontent.com/4176520/189661108-9ce4c78a-7b8f-4828-871f-121995f55b4c.png)

</details>

**Comment by huyz** [comment]
I have to invoke it several times.  The first few times the window disappears immediately. Then after a few times, the window stays up but is blank for me too.

**Comment by ellisonleao** [comment]
hey @CalebDW and @huyz can you pull latest and try again please?

**Comment by huyz** [comment]
@ellisonleao works now, thanks.

**Comment by CalebDW** [comment]
@ellisonleao, yes looks to be working now---thanks!

Although, when `pager=true` nvim freezes until I click on the window with my mouse....what is this option for?
