### ISSUE TITLE
Getting the message of old configurations at startup 

### ISSUE THREAD

**Issue by Ghasak** [ellisonleao/glow.nvim#93]
I keep getting the message: 

`glow.nvim: old configs were merged in the new config system, please update your configuration using the new setup() function. `

My Configurations: 
```lua
local M = {}

M.setup = function()
  require('glow').setup({
    glow_binary_path = "~/.local/bin",
    glow_style = "dark",
    glow_use_pager = false,
    glow_width = 80,
    glow_border = "shadow"
    vim.api.nvim_set_keymap('n', '<leader>m', ':Glow<CR>', { noremap = true, silent = true }),
  })
end

return M
```

then I call it in packer (assume the configuration above with file name: myGlowMark.lua)

```lua
  use({
   -- "npxbr/glow.nvim",
    "ellisonleao/glow.nvim",
    ft = { 'markdown' },
    config = function() require("plugins.configs.myGlowMark").setup() end
  })


```
Is there anything wrong with my configurations? 
I am using `MacBookPro14` M1.

**Comment by ellisonleao** [comment]
hey Ghazak the only remaining `glow_*` config is `glow_path` now. I saw your current is also using the default values, so just calling `require('glow').setup()` will be enough to get things started. If you need custom configs, make sure to check the default values in [README](https://github.com/ellisonleao/glow.nvim/blob/main/README.md#setup)

**Comment by Ghasak** [comment]
Thank you very much for your reply, It seems the message still be printed even when I remove all configurations by calling require('glow').setup(). 
I really appreciate your support, it doesn't bother me this message, but I wish to know if my configurations are correct? hmmm! 
I even tried to just calling the `:Glow` command directly which gave the same message.

**Comment by Ghasak** [comment]
Thank you very much for your support, it has been resolved. 
Sincere regards,
