### ISSUE TITLE
OS not supported - Windows

### ISSUE THREAD

**Issue by timii** [ellisonleao/glow.nvim#94]
Hi,

When I try to run `:Glow` it won't run for me, it only says "OS not supported"

### My config:

- nvim version:
```bash
> nvim --version
NVIM v0.7.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Features: -acl +iconv +tui
```

- Windows 10 Home 21H1 19043.2130
- `:lua print(vim.loop.os_uname().sysname)` = "Windows_NT"
- `:lua vim.pretty_print(jit.os)` = "Windows"
- I use `packer.nvim` and this is my init.lua
```lua
use {"ellisonleao/glow.nvim"}

require("glow").setup({})
```

I also saw the other issue #82, but it still doesn't work

**Comment by lioaslan** [comment]
same issue

**Comment by bnmadden9** [comment]
Chiming in to also echo, same issue!

**Comment by pynappo** [comment]
The auto-install of the glow.exe doesn't work on windows yet (uses tar/curl commands) so for now you'll probably want to download glow somewhere and add it to your $PATH. With [scoop](https://scoop.sh), `scoop install glow` does that for you.
