### ISSUE TITLE
Segmentation fault on Termux

### ISSUE THREAD

**Issue by mrtnvgr** [ellisonleao/glow.nvim#98]
```
~ :: glow
Segmentation fault
```
In neovim when I run `:Glow` command - nothing happens.
When this plugin installs a glow binary, it doesn't work, but version installed from `pkg` works fine.

```
~ :: nvim --version
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builder@4630957a93ef

Features: +acl +iconv +tui
See ":help feature-compile"
```
I use `packer.nvim`

**Comment by ellisonleao** [comment]
hey @mrtnvgr what is your OS? Can you output:

```sh
$ uname -a
```

**Comment by mrtnvgr** [comment]
> hey @mrtnvgr what is your OS? Can you output:
> 
> ```sh
> $ uname -a
> ```

```
~ :: uname -a
Linux localhost 4.4.285-Predator-Stormbreaker-X4.8-g8b7c85ef17c2 #1 SMP PREEMPT Thu Dec 23 06:06:58 CET 2021 aarch64 Android
```

**Comment by ellisonleao** [comment]
> When this plugin installs a glow binary, it doesn't work, but the version installed from pkg works fine.

Yeah, it looks like the current install script cannot identify the correct binary for your OS. Can you install it manually and make sure that `glow` binary is at your current `$PATH` please?  the plugin can figure out the rest.

**Comment by mrtnvgr** [comment]
I tried and it works, but i want to fix this install script.

Does the plugin install the latest version? I think that support has already been added later, because pkg installs version built from source, but for some reason it says that the version is 1.4.1.

```
~ :: pkg install glow
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
glow is already the newest version (1.4.1).
```

```
~ :: glow --version
glow version unknown (built from source)
```

**Comment by ellisonleao** [comment]
@mrtnvgr not sure what you are proposing. the install script should and will always work with the latest stable release. I am not going to change that if that's the case.

**Comment by mrtnvgr** [comment]
Okay... Since the problem is not in the plugin, I will close the issue. Thanks for the help!
