### ISSUE TITLE
Option to use a split instead of a floating window.

### ISSUE THREAD

**Issue by mrjones2014** [ellisonleao/glow.nvim#99]
I'd love an option to have a live-updating preview in a split window. For example, in the below screenshot, Glow preview would go on the right side.

![image](https://user-images.githubusercontent.com/8648891/208172149-f9da3bdd-32db-4017-98e9-fabc66112fdf.png)

**Comment by ellisonleao** [comment]
@mrjones2014 that's already in the future plans. We've already opened a discussion [here](https://github.com/ellisonleao/glow.nvim/discussions/78) to check possible implementations. Feel free to add your comments there
